# We want pushes to main, beta, and alpha to trigger a publish to npm for the corresponding npm dist-tag.
# Any pull request targeting deploy branches should run all tests.
on:
  push:
    branches: [main, beta, alpha]

  pull_request:
    branches: [main, beta, alpha]

jobs:
  test:
    uses: activescott/github-actions-workflows/.github/workflows/npm-tester.yml@v2
    with:
      package_dir: ./
      node_versions: "[16]"

  publish-putty:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [test]
    uses: activescott/github-actions-workflows/.github/workflows/npm-publisher.yml@npm-publisher-v4
    with:
      package_dir: packages/putty
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-dedupe-files:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [test, publish-putty]
    uses: activescott/github-actions-workflows/.github/workflows/npm-publisher.yml@npm-publisher-v4
    with:
      package_dir: packages/dedupe-files
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-organize-files-by:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [test, publish-putty]
    uses: activescott/github-actions-workflows/.github/workflows/npm-publisher.yml@npm-publisher-v4
    with:
      package_dir: packages/organize-files-by
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
