on:
  #  push:
  #    branches: [main, beta, alpha]

  pull_request:
    branches: [main, beta, alpha]

jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: install dependencies
        run: |
          npm ci

      - name: commitlint
        run: |
          echo "github.event.pull_request.base.sha: ${{ github.event.pull_request.base.sha }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
          echo git log:
          git log -10 --pretty='oneline'
          echo 
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      # for andymckay/labeler see https://github.com/marketplace/actions/simple-issue-labeler
      - name: label when commitlint fails
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'commit-message-rule-violation'

      - name: comment when commitlint fails
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.event.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for the PR! A commit message on this PR doesn't follow the conventions at https://github.com/activescott/files-and-folders/tree/main#commit-message-conventions. That might be okay but it may also not publish a package release that you intend to. This is just an FYI and maintainers can help with this though, so don't fret.'
            })

      - name: label removal when commitlint succeeds
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: andymckay/labeler@1.0.4
        with:
          remove-labels: 'commit-message-rule-violation'

      - name: comment when commitlint succeeds
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.event.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for the PR! Thanks for following our commit message conventions!'
            })
