on:
  #  push:
  #    branches: [main, beta, alpha]

  pull_request:
    branches: [main, beta, alpha]

jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: commitlint
        run: |
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo git log:
          git log -10 --pretty='oneline'
          echo 
          npx commitlint --from ${GITHUB_BASE_REF} --to ${GITHUB_SHA}

      # for andymckay/labeler see https://github.com/marketplace/actions/simple-issue-labeler
      - name: label when commitlint fails
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "commit-message-rule-violation"

      - name: label removal when commitlint succeeds
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: andymckay/labeler@1.0.4
        with:
          remove-labels: "commit-message-rule-violation"
